### ISSUE TITLE
Broken documentation page

### ISSUE THREAD

**Issue by szpak** [muravjov/bombono-dvd#2]
The Documentation page (http://www.bombono.org/Documentation) looks as follow:

```
Q1MKrH <a href="http://hzwqqqyyhuem.com/">hzwqqqyyhuem</a>,
[url=http://warhtpewkhpp.com/]warhtpewkhpp[/url],
[link=http://smhnvkgymbzd.com/]smhnvkgymbzd[/link], http://rpdzzhwdtsea.com/
```

what as I suspect is not the expected content.

**Comment by muravjov** [comment]
Thank you! 
That was spam.

**Comment by szpak** [comment]
Btw, thanks for fixing thinks in 1.2.4 - it allows to compile Bombono in Fedora 23.

**Comment by muravjov** [comment]
You are welcome.15:13, 15 апреля 2016 г., "Marcin Zajączkowski" <notifications@github.com>:Btw, thanks for fixing thinks in 1.2.4 - it allows to compile Bombono in Fedora 23. —You are receiving this because you modified the open/close state.Reply to this email directly or view it on GitHub
