### ISSUE TITLE
bombono dvd for Fedora 23 on rpmfusion appears to need updated please, thanks.

### ISSUE THREAD

**Issue by mwebb9944** [muravjov/bombono-dvd#5]
First, thank you for your work on this program - it is a great package and thank you very much!

Please be aware that the binary package posted to rpmfusion for Fedora 23 (x64) is currently giving an error saying:
dnf install bombono-dvd                                                                      
Last metadata expiration check: 0:58:22 ago on Sat May 28 19:34:33 2016.                                         
Error: nothing provides libboost_filesystem.so.1.57.0 needed by bombono-dvd-1.2.2-11.fc22.i686                     
(try to add '--allowerasing' to command line to replace conflicting packages) 

It looks like Fedora is simply using a slightly newer version of libboost:
rpm -q -a |grep -i boost
boost-thread-1.58.0-11.fc23.x86_64
boost-filesystem-1.58.0-11.fc23.x86_64
boost-program-options-1.58.0-11.fc23.x86_64
boost-regex-1.58.0-11.fc23.x86_64
boost-iostreams-1.58.0-11.fc23.x86_64
boost-system-1.58.0-11.fc23.x86_64
boost-date-time-1.58.0-11.fc23.x86_64
boost-signals-1.58.0-11.fc23.x86_64

sometimes (not in this case though) I can work around this by simply installing the RPM with the --nodeps flag and then using symbolic linking to the newer files with the older name...but in this case that didn't work.  Here's the files that it complains about when I attempted to install the RPM (without the --nodeps flag so that you can see specifically what it's warning about)
rpm -ivh bombono-dvd-1.2.2-11.fc22.x86_64.rpm 
warning: bombono-dvd-1.2.2-11.fc22.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 97f4d1c1: NOKEY
error: Failed dependencies:
        libboost_filesystem.so.1.57.0()(64bit) is needed by bombono-dvd-1.2.2-11.fc22.x86_64
        libboost_regex.so.1.57.0()(64bit) is needed by bombono-dvd-1.2.2-11.fc22.x86_64
        libboost_system.so.1.57.0()(64bit) is needed by bombono-dvd-1.2.2-11.fc22.x86_64

I hope that provides you sufficient detail - and thank you again for this wonderful program!

**Comment by muravjov** [comment]
Thanks!

As for rpmfusion and Fedora 23 (x64), the bombono binaries are evidently built with boost 1.57, and it is not right (if you can't install boost 1.57). I tested bombono  with boost up to 1.60, it works.

Please reach the rpmfusion maintainer of bombono. If you consider it is bombono' issue still, please reopen this issue.

**Comment by mwebb9944** [comment]
Thank you - I was under the mistaken impression (my fault - sorry) that you maintained the binary compilation there - I'll try running down the maintainer there.  Thank you again for this great program Muravjov!
